# Generated by Django 6.0.1 on 2026-04-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tag_include_category',
            field=models.BooleanField(default=True, help_text='Include the 3-letter category code segment.', verbose_name='Include Category Code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tag_include_company',
            field=models.BooleanField(default=True, help_text='Include the 2-letter company code segment.', verbose_name='Include Company Code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tag_include_year',
            field=models.BooleanField(default=True, help_text='Append 2-digit year at the end.', verbose_name='Include Year Suffix'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tag_prefix',
            field=models.CharField(blank=True, help_text="Optional fixed prefix for all asset tags (e.g. 'AST', 'INV'). Leave blank to use company code.", max_length=20, verbose_name='Fixed Tag Prefix'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tag_separator',
            field=models.CharField(default='-', help_text='Character(s) between tag segments.', max_length=5, verbose_name='Separator'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tag_sequence_format',
            field=models.CharField(choices=[('HEX4', '4-Digit Hex (001A)'), ('HEX6', '6-Digit Hex (00001A)'), ('NUM4', '4-Digit Number (0001)'), ('NUM5', '5-Digit Number (00001)'), ('NUM6', '6-Digit Number (000001)')], default='HEX4', help_text='Number format for the sequential counter.', max_length=10, verbose_name='Sequence Format'),
        ),
    ]
