# Generated by Django 6.0.1 on 2026-04-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_org_asset_tag_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='label_template',
            field=models.CharField(choices=[('CLASSIC', 'Classic – QR left, Barcode right'), ('COMPACT', 'Compact – QR + Tag only (small sticker)'), ('DETAILED', 'Detailed – QR, Barcode, Name, Category, Location'), ('BARCODE_ONLY', 'Barcode Only – Horizontal barcode strip')], default='CLASSIC', help_text='Default sticker label design used when printing asset labels.', max_length=20, verbose_name='Label Design'),
        ),
    ]
