# Generated by Django 6.0.1 on 2026-05-23 13:13

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.core.models.validate_logo_file_size]),
        ),
    ]
