# Generated by Django 6.0.1 on 2026-02-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('ASSET_MANAGER', 'Asset Manager'), ('AUDITOR', 'Auditor'), ('DEPT_MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee'), ('DATA_ENTRY', 'Data Entry'), ('CHECKER', 'Checker/Manager'), ('SENIOR_MANAGER', 'Senior Manager')], default='EMPLOYEE', max_length=50),
        ),
    ]
