# Generated by Django 6.0.1 on 2026-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Data Entry'), ('CHECKER', 'Checker/Manager'), ('SENIOR_MANAGER', 'Senior Manager')], default='EMPLOYEE', max_length=50),
        ),
    ]
