# Generated by Django 6.0.1 on 2026-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(blank=True, choices=[('STRAIGHT_LINE', 'Straight Line'), ('REDUCING_BALANCE', 'Reducing Balance')], default='STRAIGHT_LINE', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='maintenance_frequency_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Frequency in days'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
    ]
