# Generated by Django 6.0.1 on 2026-01-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_currency_alter_asset_depreciation_method_and_more'),
        ('locations', '0002_branch_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.branch'),
        ),
    ]
