# Generated by Django 6.0.1 on 2026-01-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='building',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='room',
        ),
    ]
