# Generated by Django 6.0.1 on 2026-01-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_asset_branch_remove_asset_building_and_more'),
        ('locations', '0003_building_floor_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.branch'),
        ),
        migrations.AddField(
            model_name='asset',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.building'),
        ),
        migrations.AddField(
            model_name='asset',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.floor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.room'),
        ),
    ]
