# Generated by Django 6.0.1 on 2026-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_branch_asset_building_asset_floor_asset_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depreciation_method',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('REDUCING_BALANCE', 'Reducing Balance')], default='STRAIGHT_LINE', max_length=50),
        ),
    ]
