# Generated by Django 6.0.1 on 2026-01-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_category_depreciation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, default='AED', max_length=10),
        ),
    ]
