# Generated by Django 6.0.1 on 2026-02-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='expected_units',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='units_consumed',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='default_expected_units',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='default_salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(blank=True, choices=[('STRAIGHT_LINE', 'Straight Line'), ('DOUBLE_DECLINING', 'Double Declining Balance'), ('SYD', 'Sum of Years Digits'), ('UNITS_OF_PRODUCTION', 'Units of Production'), ('REDUCING_BALANCE', 'Reducing Balance')], default='STRAIGHT_LINE', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='depreciation_method',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DOUBLE_DECLINING', 'Double Declining Balance'), ('SYD', 'Sum of Years Digits'), ('UNITS_OF_PRODUCTION', 'Units of Production'), ('REDUCING_BALANCE', 'Reducing Balance')], default='STRAIGHT_LINE', max_length=50),
        ),
    ]
