# Generated by Django 6.0.1 on 2026-02-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_expected_units_asset_units_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual depreciation rate in percentage (e.g. 20.00 for 20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation rate in percentage (e.g. 20.00 for 20%). Overrides Useful Life if set.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
