# Generated by Django 6.0.1 on 2026-02-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_depreciation_rate_category_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='depreciation_rate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='depreciation_rate',
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(blank=True, choices=[('STRAIGHT_LINE', 'Straight Line'), ('DOUBLE_DECLINING', 'Double Declining Balance'), ('SYD', 'Sum of Years Digits'), ('UNITS_OF_PRODUCTION', 'Units of Production')], default='STRAIGHT_LINE', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='depreciation_method',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DOUBLE_DECLINING', 'Double Declining Balance'), ('SYD', 'Sum of Years Digits'), ('UNITS_OF_PRODUCTION', 'Units of Production')], default='STRAIGHT_LINE', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='useful_life_years',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
