# Generated by Django 6.0.1 on 2026-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_remove_asset_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Code'),
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='label_type',
            field=models.CharField(choices=[('QR_CODE', 'QR Code'), ('BARCODE', 'Barcode'), ('RFID', 'RFID'), ('NONE', 'None')], default='NONE', max_length=50, verbose_name='Label Type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(help_text='Unique Asset ID (Autogenerated)', max_length=100, verbose_name='Asset ID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('METAL', 'Metal'), ('NON_METAL', 'Non-Metal')], default='METAL', max_length=20),
        ),
    ]
