# Generated by Django 6.0.1 on 2026-02-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_asset_code_asset_custom_asset_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='asset',
            name='erp_asset_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ERP Asset Number'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset', verbose_name='Parent Asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('TAGGABLE', 'Taggable'), ('BUILDING_IMPROVEMENTS', 'Building Improvements'), ('NTA', 'NTA'), ('CAPEX', 'CAPEX')], default='TAGGABLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('DAMAGED', 'Damaged'), ('UNDER_REPAIR', 'Under Repair')], default='NEW', max_length=20, verbose_name='Asset Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='label_type',
            field=models.CharField(choices=[('METAL', 'Metal'), ('NON_METAL', 'Non-Metal')], default='NON_METAL', max_length=50, verbose_name='Label Type'),
        ),
    ]
