# Generated by Django 6.0.1 on 2026-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_asset_asset_remarks_asset_brand_new_asset_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_placed_in_service',
            field=models.DateField(blank=True, null=True, verbose_name='Date Place in Service'),
        ),
        migrations.AddField(
            model_name='asset',
            name='do_date',
            field=models.DateField(blank=True, null=True, verbose_name='DO Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='do_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='DO Number'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance End Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Start Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Maintenance End Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Maintenance Start Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='PO Number'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tagged_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tagged Date'),
        ),
    ]
