# Generated by Django 6.0.1 on 2026-02-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_asset_date_placed_in_service_asset_do_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='amc_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/amc/', verbose_name='Upload AMC Contract'),
        ),
        migrations.AddField(
            model_name='asset',
            name='delivery_note_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/delivery_notes/', verbose_name='Upload Delivery Note'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='assets/images/', verbose_name='Upload Image'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/insurance/', verbose_name='Upload Insurance Contract'),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/invoices/', verbose_name='Upload Invoice/Contract'),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/po/', verbose_name='Upload Purchase Order'),
        ),
    ]
