# Generated by Django 6.0.1 on 2026-02-18 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_asset_amc_file_asset_delivery_note_file_asset_image_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('ASSET_CREATE', 'Asset Creation'), ('ASSET_UPDATE', 'Asset Update'), ('ASSET_TRANSFER', 'Asset Transfer'), ('ASSET_RETIRE', 'Asset Retirement'), ('ASSET_WRITE_OFF', 'Asset Write-off'), ('BULK_IMPORT', 'Bulk Import')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CHECKER_APPROVED', 'Checker Approved'), ('CHECKER_REJECTED', 'Checker Rejected'), ('SENIOR_APPROVED', 'Senior Manager Approved'), ('SENIOR_REJECTED', 'Senior Manager Rejected'), ('APPROVED', 'Fully Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Asset details submitted for approval')),
                ('comments', models.TextField(blank=True, help_text="Requester's comments or notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='assets.asset')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('approval_level', models.CharField(choices=[('CHECKER', 'Checker'), ('SENIOR_MANAGER', 'Senior Manager')], max_length=50)),
                ('comments', models.TextField(blank=True, help_text='Approval comments and feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='assets.approvalrequest')),
            ],
            options={
                'verbose_name': 'Approval Log',
                'verbose_name_plural': 'Approval Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
