# Generated by Django 6.0.1 on 2026-02-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_assettransfer'),
        ('assets', '0020_assettransfer'),
    ]

    operations = [
    ]
