# Generated by Django 6.0.1 on 2026-02-21 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_merge_0019_assettransfer_0020_assettransfer'),
        ('core', '0001_initial'),
        ('locations', '0004_region_site_location_sublocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='movement_reason',
            field=models.CharField(blank=True, help_text='Specific reason for this movement', max_length=255),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='request_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_from_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from_building', to='locations.building'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from_company', to='assets.company'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_from_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from_custodian', to='assets.custodian'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_from_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from_floor', to='locations.floor'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_from_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from_region', to='locations.region'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_from_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from_room', to='locations.room'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_from_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_from_site', to='locations.site'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
