# Generated by Django 6.0.1 on 2026-02-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_assettransfer_is_deleted_and_more'),
        ('locations', '0004_region_site_location_sublocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='requester_name',
            field=models.CharField(blank=True, help_text='Name of the requester (free text)', max_length=255),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transfer_description',
            field=models.TextField(blank=True, help_text='Short description for the transfer request'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transfer_no',
            field=models.CharField(blank=True, help_text='Optional transfer reference number', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_to_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_to_building', to='locations.building'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_to_company', to='assets.company'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_to_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_to_custodian', to='assets.custodian'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_to_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_to_floor', to='locations.floor'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_to_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_to_region', to='locations.region'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_to_room', to='locations.room'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_to_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_to_site', to='locations.site'),
        ),
    ]
