# Generated by Django 6.0.1 on 2026-02-22 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_assettransfer_requester_name_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Disposal Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('disposal_method', models.CharField(choices=[('SCRAP', 'Scrap'), ('DONATE', 'Donate'), ('SELL', 'Sell'), ('RECYCLE', 'Recycle'), ('DISCARD', 'Discard'), ('OTHER', 'Other')], default='SCRAP', help_text='Method of disposal', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Reason for disposal (e.g., End of life, Damaged, Obsolete)')),
                ('disposal_date', models.DateField(blank=True, help_text='Planned or actual disposal date', null=True)),
                ('estimated_salvage_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value if sold or donated', max_digits=12, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='assets.asset')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
