# Generated by Django 6.0.1 on 2026-02-22 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_assetdisposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdisposal',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals_manager_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='manager_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for manager rejection'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for admin rejection'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Manager Approval'), ('MANAGER_APPROVED', 'Manager Approved, Awaiting Admin'), ('APPROVED', 'Admin Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Disposal Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
