# Generated by Django 6.0.1 on 2026-03-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_asset_org_deleted_idx_asset_org_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='barcode_image',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='assets/barcodes/', verbose_name='Barcode Image'),
        ),
        migrations.AddField(
            model_name='asset',
            name='label_image',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='assets/labels/', verbose_name='Combined Label'),
        ),
        migrations.AddField(
            model_name='asset',
            name='qr_code_image',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='assets/qr_codes/', verbose_name='QR Code Image'),
        ),
    ]
