# Generated by Django 6.0.1 on 2026-04-20 04:44

from django.conf import settings
from django.db import migrations, models


def normalize_empty_asset_codes(apps, schema_editor):
    """Convert empty string asset_code values to NULL and deduplicate existing codes."""
    Asset = apps.get_model('assets', 'Asset')
    # Set empty strings to NULL
    Asset.objects.filter(asset_code='').update(asset_code=None)
    
    # Deduplicate: for each (org, asset_code) with duplicates, append -2, -3, etc.
    from django.db.models import Count
    dupes = (
        Asset.objects
        .filter(asset_code__isnull=False)
        .values('organization', 'asset_code')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    for dupe in dupes:
        assets = list(
            Asset.objects
            .filter(organization=dupe['organization'], asset_code=dupe['asset_code'])
            .order_by('created_at')
        )
        # Keep the first one as-is, rename the rest
        for i, asset in enumerate(assets[1:], start=2):
            asset.asset_code = f"{dupe['asset_code']}-{i}"
            asset.save(update_fields=['asset_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_add_barcode_qr_fields'),
        ('core', '0001_initial'),
        ('locations', '0004_region_site_location_sublocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='custom_asset_tag',
        ),
        migrations.RunPython(normalize_empty_asset_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('asset_code', ''), _negated=True), ('asset_code__isnull', False)), fields=('organization', 'asset_code'), name='unique_asset_code_per_org'),
        ),
    ]
