# Generated by Django 6.0.1 on 2026-04-20 05:30

from django.db import migrations, models


def populate_asset_codes(apps, schema_editor):
    """Fill empty/null asset_code with asset_tag so the field can become required."""
    Asset = apps.get_model('assets', 'Asset')
    from django.db.models import F
    # Set asset_code = asset_tag for all rows where asset_code is null or empty
    Asset.objects.filter(
        models.Q(asset_code__isnull=True) | models.Q(asset_code='')
    ).update(asset_code=F('asset_tag'))


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_remove_custom_asset_tag_unique_asset_code'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_asset_code_per_org',
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('organization', 'asset_tag')},
        ),
        migrations.RunPython(populate_asset_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(max_length=100, verbose_name='Asset Code'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('organization', 'asset_code'), ('organization', 'asset_tag')},
        ),
    ]
