# Generated by Django 6.0.1 on 2026-04-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_asset_code_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cached_accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Cached Accumulated Depreciation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cached_nbv',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Cached Net Book Value'),
        ),
    ]
