# Generated by Django 6.0.1 on 2026-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_add_cached_depreciation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_tagged',
            field=models.BooleanField(default=False, verbose_name='Is Tagged'),
        ),
    ]
