# Generated by Django 6.0.1 on 2026-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_fix_assettransfer_missing_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='cached_accumulated_depreciation',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cached_nbv',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_tagged',
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='asset_snapshot',
            field=models.JSONField(blank=True, help_text='Full asset details captured at the time of disposal approval', null=True),
        ),
    ]
