# Generated by Django 6.0.1 on 2026-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0033_add_asset_snapshot_to_disposal'),
        ('core', '0004_organization_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('organization', 'asset_tag')},
        ),
        migrations.RemoveField(
            model_name='assetdisposal',
            name='asset_snapshot',
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Code'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='label_type',
            field=models.CharField(choices=[('RFID', 'RFID'), ('QR_CODE', 'QR Code'), ('BARCODE', 'Barcode')], default='RFID', max_length=50, verbose_name='Label Status'),
        ),
    ]
