# Generated by Django 6.0.1 on 2026-05-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_label_type_rfid_qrcode_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='label_type',
            field=models.CharField(blank=True, default='QR_CODE,BARCODE', max_length=200, verbose_name='Label Status'),
        ),
    ]
