# Generated by Django 6.0.1 on 2026-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0035_label_type_multi_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tagging_status',
            field=models.CharField(choices=[('TAGGED', 'Tagged'), ('UNTAGGED', 'Untagged')], default='UNTAGGED', max_length=10, verbose_name='Tagging Status'),
        ),
    ]
