# Generated by Django 6.0.1 on 2026-05-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0036_add_tagging_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='label_type',
            field=models.CharField(blank=True, default='QR_CODE,BARCODE', max_length=200, verbose_name='Label Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tagging_status',
            field=models.CharField(choices=[('TAGGED', 'Tagged'), ('UNTAGGED', 'Untagged')], default='UNTAGGED', max_length=10, verbose_name='Label Status'),
        ),
    ]
