# Generated by Django 6.0.1 on 2026-05-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0037_alter_asset_label_type_alter_asset_tagging_status'),
        ('core', '0004_organization_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_category_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
    ]
