# Generated by Django 6.0.1 on 2026-05-16 12:28

from django.db import migrations, models


def deduplicate_category_and_subcategory(apps, schema_editor):
    Category = apps.get_model('assets', 'Category')
    SubCategory = apps.get_model('assets', 'SubCategory')
    Asset = apps.get_model('assets', 'Asset')

    # 1) Merge duplicate Categories by (organization_id, name).
    category_groups = {}
    for category in Category.objects.all().order_by('id'):
        key = (category.organization_id, category.name)
        category_groups.setdefault(key, []).append(category)

    for (_, _), categories in category_groups.items():
        if len(categories) <= 1:
            continue

        keeper = categories[0]
        duplicates = categories[1:]

        for duplicate in duplicates:
            # Move dependents first, then remove duplicate category.
            SubCategory.objects.filter(category_id=duplicate.id).update(category_id=keeper.id)
            Asset.objects.filter(category_id=duplicate.id).update(category_id=keeper.id)
            duplicate.delete()

    # 2) Merge duplicate SubCategories by (category_id, name).
    subcategory_groups = {}
    for subcategory in SubCategory.objects.all().order_by('id'):
        key = (subcategory.category_id, subcategory.name)
        subcategory_groups.setdefault(key, []).append(subcategory)

    for (_, _), subcategories in subcategory_groups.items():
        if len(subcategories) <= 1:
            continue

        keeper = subcategories[0]
        duplicates = subcategories[1:]

        for duplicate in duplicates:
            Asset.objects.filter(sub_category_id=duplicate.id).update(sub_category_id=keeper.id)
            duplicate.delete()


def noop_reverse(apps, schema_editor):
    # Data deduplication is not safely reversible.
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('assets', '0037_alter_asset_label_type_alter_asset_tagging_status'),
        ('core', '0004_organization_is_active'),
    ]

    operations = [
        migrations.RunPython(deduplicate_category_and_subcategory, noop_reverse),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_category_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
    ]
