# Generated by Django 6.0.1 on 2026-05-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0038_category_unique_category_name_per_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='assets.subgroup'),
        ),
    ]
