# Generated by Django 6.0.1 on 2026-05-20 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0040_assetdisposal_batch_reference'),
        ('core', '0004_organization_is_active'),
        ('locations', '0005_department_unique_org_branch_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RFID Tag'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['rfid_tag'], name='assets_asse_rfid_ta_1b672e_idx'),
        ),
    ]
