# Generated by Django 6.0.1 on 2026-08-25 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0043_asset_barcode_payload_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdisposal',
            name='estimated_salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value if sold or donated', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
